function(Myfunction FirstArg)
    message("Function: ${CAMKE_CURRENT_FUNCTION}")
    message("File:${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
    message("FirstArg:${FirstArg}")
    set(FirstArg "new value")
    message("FirstArg again:${FirstArg}")
    message("ARGV0:${ARGV0} ARGV1:${ARGV1} ARGV:${ARGV}")
endfunction()

set(FirstArg "first value")
MyFunction("Value1" "Value2")
message("FirstArg in global scope: ${FirstArg}")
